# Generated by Django 6.0.2 on 2026-02-07 16:35

import django.core.validators
import django.utils.timezone
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.CharField(max_length=300)),
                ('listaElementos', django_mongodb_backend.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, null=True)),
            ],
            options={
                'db_table': 'categorias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('categoriaCode', models.IntegerField()),
                ('temporadaCode', models.IntegerField()),
                ('posicion', models.CharField(blank=True, max_length=50, null=True)),
                ('afinidad', models.CharField(blank=True, max_length=50, null=True)),
                ('equipos', django_mongodb_backend.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True)),
                ('imageUrl', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'elementos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.CharField(max_length=300)),
                ('imageUrl', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'equipos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=150)),
                ('categoriaCode', models.IntegerField()),
                ('rankinLista', django_mongodb_backend.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'rankings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=150)),
                ('elementoCode', models.IntegerField()),
                ('puntuacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'reviews',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'temporadas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('usuario', 'Usuario')], default='usuario', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
